/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/home-stage-1` | `/home-stage-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/home-stage-2` | `/home-stage-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/questions` | `/questions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/splash` | `/splash`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/home-stage-1` | `/home-stage-1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/home-stage-2` | `/home-stage-2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/questions` | `/questions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/splash` | `/splash`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/home-stage-1${`?${string}` | `#${string}` | ''}` | `/home-stage-1${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/home-stage-2${`?${string}` | `#${string}` | ''}` | `/home-stage-2${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/questions${`?${string}` | `#${string}` | ''}` | `/questions${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/splash${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/home-stage-1` | `/home-stage-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/home-stage-2` | `/home-stage-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/questions` | `/questions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/splash` | `/splash`; params?: Router.UnknownInputParams; };
    }
  }
}
