name: Backend Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Create .env file
      run: |
        cd Back-end
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env
        echo "USE_LOCALTUNNEL='false'" >> .env
        echo "DB_PATH='./testDB.db'" >> .env
        
    - name: Install Dependencies
      working-directory: ./Back-end
      run: npm install
      
    - name: Start Server
      working-directory: ./Back-end
      run: npm start &
        
    - name: Wait for server
      run: sleep 5
      
    - name: Run Tests
      run: |
        pip install pytest requests
        python -m pytest tests/test_api.py -v